export default [
  {
    ignores: [
      'scripts/midi.js',
      'scripts/verovio-toolkit-wasm.js',
      'scripts/soundfont-player.js',
      'scripts/soundfont-player.min.js',
      'scripts/libtimidity-for-worklet.js',
      'soundfonts/**/*.js',
    ],
  },
  {
    files: ['scripts/**/*.js'],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        DOMParser: 'readonly',
        XMLSerializer: 'readonly',
        FileReader: 'readonly',
        AudioContext: 'readonly',
        AudioWorkletNode: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Int32Array: 'readonly',
        Uint8Array: 'readonly',
        Uint32Array: 'readonly',
        Float32Array: 'readonly',
        Promise: 'readonly',
        Math: 'readonly',
        atob: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        registerProcessor: 'readonly',
        AudioWorkletProcessor: 'readonly',
        sampleRate: 'readonly',
        verovio: 'readonly',
        MIDIjs: 'readonly',
        Soundfont: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'no-console': 'off',
      'no-var': 'warn',
    },
  },
]
